---
services:
  db:
    image: guthulavasuu/projectrepo:dbimage
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: guthulavasuu/projectrepo:authimage
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    

  book_service:
    image:  guthulavasuu/projectrepo:bookimage
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db
  borrow_service:
    image: guthulavasuu/projectrepo:borrowimage
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge
